### ISSUE TITLE
Channel.close with tls-mirage raises an End_of_file exception

### ISSUE THREAD

**Issue by juanchanco** [mirage/mirage-channel#12] opened 2016-10-24 17:43 UTC
This was originally filed under https://github.com/mirage/mirage-http/issues/28
The problem is with a Mirage unikernel running https under zen. Closing the connection give the following error:

```
Fatal error: exception (Failure "TLS.server_of_flow: End-of-file!")
Raised at file "format.ml", line 241, characters 41-52
Called from file "format.ml", line 482, characters 6-24
Mirage exiting with status 2
Do_exit called!
```

When mirage-http calls Channel.close, causes the Channel to flush, which writes to it's internal Flow. Digging further, it seems that by this point, when using tls_mirage, the Flow is already in a closed state, and raises an End_of_file exception. It looks like this bug came up a while ago here: https://github.com/mirage/mirage-net-xen/issues/39 though I'm not sure what the resolution was. It seems like the decision was that the calling code should handle the exception.

**Comment by hannesm** [comment] 2017-10-07 22:28
sorry for the late reply, I just stumbled upon this issue.  Since MirageOS 3 was released in February 2017, there shouldn't be any exceptions raised anymore.  I'll close this issue, please feel free to reopen if you're able to reproduce the problem with mirage 3.

**Closed by hannesm** 2017-10-07 22:28 UTC
